[tool.poetry]
name = "codex"
version = "0.1.0"
description = "Computational Oracle for Data Encoding and eXploratio"
authors = ["SwiftyOS <craigswift13@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.5.0"
sqlmodel = "^0.0.14"
pgvector = "^0.2.4"
psycopg2 = "^2.9.9"


[tool.poetry.group.dev.dependencies]
black = "^23.12.0"
isort = "^5.13.2"
flake8 = "^6.1.0"
pytest = "^7.4.3"
pre-commit = "^3.6.0"
ipython = "^8.18.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
